export const PROD_CHANGE = 'PROD_CHANGE';
export const SET_FILTER = 'SET_FILTER';
export const INSERT_PRODUCT = 'INSERT_PRODUCT';
export const INITIAL_STATE = 'INITIAL_STATE';
export const CHANGE_STATE_PRODUCT = 'CHANGE_STATE_PRODUCT';

export const USER_FETCHED = 'USER_FETCHED';
export const USER_FETCHED_ANONIMO = 'USER_FETCHED_ANONIMO';
export const USER_FETCHED_ADMIN = 'USER_FETCHED_ADMIN';

export const TOKEN_VALIDATED = 'TOKEN_VALIDATED';
export const NEW_ID_PRODUCT = 'NEW_ID_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DEL_PRODUCT = 'DEL_PRODUCT';