version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:lts
      
jobs:
  build-my-project:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          yarn

workflows:
  my-custom-workflow:
    jobs:
      - build-my-project